# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "opscode-centos-6.5"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
  # Chef Clientの最新版を利用可能にする
  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    # (d1)クックブックの配置場所を指定
    chef.cookbooks_path = "./cookbooks"
    # (d2)Attributeの定義
    chef.json = {
      nginx: {
        env: "ruby"
      },
      fluentd: {
        installer: "rpm"
      },
      mysql: {
        server_root_password: 'rootpass'
      }
    }
    # (d3)適用するクックブックの定義
    chef.run_list = %w[
      recipe[yum-epel]
      recipe[nginx]
      recipe[mysql]
      recipe[fluentd]
    ]
  end
end
