name             'acme-trac'
maintainer       'Ryuzee'
maintainer_email 'ryuzee@gmail.com'
license          'MIT'
description      'Installs/Configures acme-trac'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'iptables'
depends 'subversion'
depends 'trac'
depends 'apache2'
